services:
  - type: web
    name: coffe-codes-and-anything-else
    env: ruby
    buildCommand: "./bin/render-build.sh"
    preDeployCommand: "bundle exec rails db:prepare"
    startCommand: "bundle exec rails server"
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2
      # DATABASE_URL will be added manually from Render dashboard
