services:
  - type: web
    name: coffe-codes-and-anything-else
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails server"
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2
      - key: DATABASE_URL
        fromDatabase:
          name: coffe-blog-db
          property: connectionString

databases:
  - name: coffe-blog-db
    databaseName: coffe_blog_production
    user: coffe_blog_user
    plan: free
